### PR TITLE
README updated to include a brief description of our project aim

### PR DESCRIPTION
**Pull request by DevashishDhyani**
**Description**
README file updated to include description of what our web app is meant to achieve.

**Checklist**
- [x] Docs have been added/updated if needed

### CODE REVIEW

**Comment by SeanSpires** [comment]
Looks good to me

**Review by SeanSpires — APPROVED** [review]

**Comment by skmu104** [comment]
@DevashishDhyani Im currently waiting on my README template changes to go through.  Might have to re-edit the document after my changes go through so that it doesn't get overwritten.

**Review by williamlixu — APPROVED** [review]
LGTM, thanks for writing this up!

**Review by dder725 — APPROVED** [review]
Thank you for doing that, will merge after @skmu104 PR is merged  :)

**Comment by williamlixu** [comment]
Fixed the merge conflict due to #69 and merging now

**Pull request merged**
