### PR TITLE
Setup page templates, redux and routing

### LINKED ISSUE #25: Setup Frontend Page Templates
**User Story**
For example: 
As a developer
I want to have a base page for the app
So future pages can use this template to keep a consistent display of the app

**Priority**
[x]: High
[]: Medium
[]: Low

**Describe the solution you want to implement**
The aim is to use redux for state management to handle app-wide state, and to use routers to route and switch between pages. 

**Describe alternatives you've considered**
Other state management methods that we could use is React Context, but we realise that we are currently learning redux and have more familiarity. State management is also important in routing between multiple pages.

### PR DESCRIPTION
**Pull request by vee-christella**
Closes #25 - mob programmed with @williamlixu, @jake-good, @pabloSushibar 

**Description**

This PR creates a very basic non-styled page template that outlines the skeleton of the frontend webapp. Major features implemented in this PR include:
- Adding and setting up a redux skeleton template (currently non-functional as nothing uses state at the moment)
- Setting up routing and navigation using SPA. Compared to MPA, SPA was preferable due to its simplicity and works well with our basic app
- Cleared out initial react template
- Added basic page hierarchy and non-styles pages

**Testing**

We checked that the navigation works by routing through its respective page when links/buttons are clicked. In terms of redux, a initial counter example is used as a stub to make sure that state management is operational.

There is no currently styling that requires any other frontend tests as of now (such as snapshot tests).

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [ ] Docs have been added/updated if needed

### CODE REVIEW

**Review by jake-good — APPROVED** [review]
Looks good to me.

**Review by babe269 — APPROVED** [review]
Looks good!

**Review by williamlixu — APPROVED** [review]
LGTM

**Review by tgre605 — APPROVED** [review]
Looks good to me

**Review by pabloSushibar — APPROVED** [review]
Looks absolutely fantastic. Great work team!

**Pull request merged**
