### PR TITLE
Feature/bills pagination number of bills

### LINKED ISSUE #161: Backend API pagination returns total bills
**User Story**
For example: 
As a developer,
I want the backend response for bills to return total bills,
so that I can get the number of pages required for pagination in the front end

**Priority**
[]: High
[x]: Medium
[]: Low

**Describe the solution you want to implement**
Have the backend response return a total number of bills for pagination

**Describe alternatives you've considered**
n/a

**Issue Dependencies**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by kaplunket**
Closes #161

**Description**
Added a num_of_bills field to the endpoint

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [x] Docs have been added/updated if needed

### CODE REVIEW

**Review by GrunWong — APPROVED** [review]
LGTM

**Review by ErnWong — COMMENTED** [review]
Just a side note. The first two commits are old commits part of a previous PR that was already merged.

image

It's okay to leave them here for this PR this time, but I reckon it'll be good to avoid it in the future because it could lead to evil merges (where the old commits overrides a new change) and misleading documentation when people look back into this PR and think that this PR is about adding pagination API to the backend.

### Tips to avoid old commits appearing in new PR

Before you start making new changes, update your `master` with upstream's changes, and make a *new* feature branch off from `master`. Don't start working from an existing feature branch. 

### What to do if you have already started in an existing feature branch

You would need to rebase the desired commits onto upstream master. Something like the following command will work for this PR, for example:

```sh
git rebase --onto upstream/master 20091f7 feature/bills-pagination-page_num
```

The above command takes the commits from `20091f7` (exclusive) to the end of `feature/bills-pagination-page_num` (inclusive), and replays them onto the tip of `upstream/master`.

See [the second bullet point of this section from the wiki](https://github.com/se701-group6/A2/wiki/Workflow-and-git-guide#advanced-rebasing) for more information.

**Comment by kaplunket** [comment]
Thanks, Ernest, I was wondering why the old commits were showing up!

**Review by ParieMalhotra — APPROVED** [review]
This looks good to me :)

**Pull request merged**
