### PR TITLE
Created Code-of-conduct

### LINKED ISSUE #2: Add code of conduct

### PR DESCRIPTION
**Pull request by rfro377**
Created Code of conduct file from template Code Covenant

### CODE REVIEW

**Review by SeanSpires — APPROVED** [review]
COC looks good to me.

**Review by williamlixu — APPROVED** [review]
Looks good to me!

**Review by dder725 — APPROVED** [review]
Looks great, awesome job @rfro377 !

**Review by margeobur — APPROVED** [review]
Cool cool

**Review by skmu104 — APPROVED** [review]
looks good to me

**Pull request merged**
