### PR TITLE
Algorithms/Diagrams added in a docx file 

### LINKED ISSUE #52: Feature Request: Algorithm needed for Front-End Development and Future Work
**User Story**
As a developer
I want to add logic for the Splitting of Bills, so that the
Front end Developers can use it. 
Also, algorithms for future use have been added.

**Priority**
[]: Medium

**Describe the solution you want to implement**
I want to add logic for the Splitting of Bills.

**Describe alternatives you've considered**
Reaching zero transition states before we changed the front end usage.

**Issue Dependencies**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by DevashishDhyani**
**Description**
-Word document has been included which contains future algorithms. This needs to be updated till we reach a final version.
The document covers scenarios that the web application must be able to handle in the future. It also has a number of readings/references I found useful while researching into this topic. 
Two solutions (one with entirety of C++ code) have been added in.

**Checklist**
- [ ] Docs have been added/updated

### CODE REVIEW

**Comment by dder725** [comment]
Could you please edit the name of this PR to be more descriptive? Same with the body, i.e. what exactly has been added, what needs to be updated, etc.

**Comment by williamlixu** [comment]
It's probably not good to put a word doc into the repo, is it possible for this information to go on the wiki instead?

**Comment by DevashishDhyani** [comment]
> Could you please edit the name of this PR to be more descriptive? Same with the body, i.e. what exactly has been added, what needs to be updated, etc.

Updated just now. Both the description and the file.

**Comment by DevashishDhyani** [comment]
> It's probably not good to put a word doc into the repo, is it possible for this information to go on the wiki instead?

Will do soon.

**Comment by DevashishDhyani** [comment]
Wiki is still pending for this.

**Comment by DevashishDhyani** [comment]
Once the docx file is verified, can one of the Documentation people copy over the contents from the file onto a Wiki page following the appropriate style for this project?
@skmu104 @rfro377

**Comment by ljcnz** [comment]
LGTM 👍

**Comment by williamlixu** [comment]
Added the doc to the wiki here: https://github.com/SOFTENG701G1/A1/wiki/Splitting-Multiple-Bills
Cheers for the research, hopefully the team that picks up our project can use it and implement the algorithm!

**Pull request closed without merging**
