### PR TITLE
Corrected sign-up page to match sign in page issue #68

### LINKED ISSUE #68: Bug report: 'Sign in' title appears on the sign up page
**Describe the bug**
When I am on the sign up page, the 'sign in' title appears on top of the input boxes

**To Reproduce**
1. Go to '/#/SignUp'
2. 'Sign in' appears on top of the input boxes

**Severity**
Mark with an x.
[x]: Minor effect eg. graphical
[]: Functional error eg. App does not function correctly
[]: Severe eg. Crashing

**Reproducibility**
Mark with an x.
[x]: Consistent
[]: Occasional
[]: Cannot reproduce at the moment eg. unsure

**Expected behavior**
Nothing appears on top of the input boxes

**Screenshots, Images and Traces**
signInBug

**Conditions**
No specific conditions

**Issue Dependencies**
#20 

**Additional context**

### PR DESCRIPTION
**Pull request by tgre605**
Closes #68 

**Description**

Corrected sign up page to match design of sign in page. Also corrected label above text fields to say sign up, instead of sign in

**Testing**

Works the same as sign in page, following exact same design patterns.

**Checklist**

- [x] I have tested my change
- [x] Code builds successfully and all tests pass
- [x] Docs have been added/updated if needed

### CODE REVIEW

**Review by babe269 — COMMENTED** [review]
Sorry If I'm being stupid but what are the xml/iml files for?

**Comment by tgre605** [comment]
Apologies, they weren't meant to be added

**Review by babe269 — APPROVED** [review]
looks good

**Comment by vee-christella** [comment]
Hey sorry to intervene into this PR, would it be possible to rename the file to `Login.js` (that's what we'll be using instead fo SignUp right?)

**Comment by tgre605** [comment]
@vee-christella we already have a Login.js page for logging in from an existing account. This PR implements the sign up page for creating an account

**Comment by vee-christella** [comment]
@tgre605  Oh sorry! Totally didn't see it. Is there a reason why the component function is also called `Login()`? Usually we match filenames with the component names but if it's intentional then that's allgood!

**Review by vee-christella — APPROVED** [review]

**Review by williamlixu — APPROVED** [review]
LGTM, let's try clean up the user experience because right now it is confusing the sign up button doesn't actually sign you up but takes you to a new page.

**Pull request merged**
